name: Metadata Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate-json-schema:
    name: Validate the Metadata JSON schema
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v2.3.1
        with:
          base_dir: mainnet
          json_schema: ./schemas/metadata.schema.json
          json_exclude_regex: ^(main|test){1}net\/\d\/(?!metadata\.json$).*
          use_gitignore: false

  fetch-modified-files:
    name: Fetch modified files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Set outputs
        id: setVariables
        run: |
          echo "::set-output name=matrix::${{ steps.changed-files.outputs.all_changed_files }}"

  validate-metadata:
    name: Validate the Source Builder 
    needs: [fetch-modified-files]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{fromJson(needs.fetch-modified-files.outputs.matrix)}}

    steps:
      - name: Output
        run: | 
          echo ${{ matrix.file }}
