name: Metadata Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate-json-schema:
    name: Validate the Metadata JSON schema
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v2.3.1
        with:
          base_dir: mainnet
          json_schema: ./schemas/metadata.schema.json
          json_exclude_regex: ^(main|test){1}net\/\d\/(?!metadata\.json$).*
          use_gitignore: false

  fetch-modified-metadata:
    name: Fetch modified metadata
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Set metadata files
        id: setfiles
        run: |
          FILES_ARRAY=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            FILE_NAME=$(basename $file)
            if [ $FILE_NAME != "metadata.json" ]; then
                continue
            fi
            FILES_ARRAY+="$file,"
          done
          FILES_ARRAY=$(echo $FILES_ARRAY | jq -R -s -c 'split(",")[:-1]')
          echo "metadata_files=${FILES_ARRAY}" >> $GITHUB_OUTPUT
    outputs:
      metadata_files: ${{ steps.setfiles.outputs.metadata_files }}

  build-binary:
    name: Build contract binary
    needs: [fetch-modified-metadata]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(needs.fetch-modified-metadata.outputs.metadata_files) }}

    steps:
      - name: Checking out ${{ matrix.file }}
        uses: actions/checkout@v3
        with:
          sparse-checkout: ${{ matrix.file }}

      - name: Output contents of ${{ matrix.file }}
        id: setmetadata
        run: |
          SOURCE=$(cat ${{ matrix.file }} | jq -r '.source')
          if [ -z "$SOURCE" ]; then
              continue
          fi
          SOURCE_REPO=$(cat ${{ matrix.file }} | jq -r '.source.repository' | sed 's/https:\/\/github.com\///')
          SOURCE_TAG=$(cat ${{ matrix.file }} | jq -r '.source.tag')
          echo "source_repo=$SOURCE_REPO" >> $GITHUB_OUTPUT
          echo "source_tag=$SOURCE_TAG" >> $GITHUB_OUTPUT

          SOURCE_BUILDER=$(cat ${{ matrix.file }} | jq -r '.source_builder')
          if [ -z "$SOURCE_BUILDER" ]; then
              continue
          fi
          SOURCE_BUILDER_IMAGE=$(cat ${{ matrix.file }} | jq -r '.source_builder.image')
          SOURCE_BUILDER_TAG=$(cat ${{ matrix.file }} | jq -r '.source_builder.tag')
          SOURCE_BUILDER_CONTRACT_NAME=$(cat ${{ matrix.file }} | jq -r '.source_builder.contract_name')
          echo "source_builder_image=$SOURCE_BUILDER_IMAGE" >> $GITHUB_OUTPUT
          echo "source_builder_tag=$SOURCE_BUILDER_TAG" >> $GITHUB_OUTPUT
          echo "source_builder_contract_name=$SOURCE_BUILDER_CONTRACT_NAME" >> $GITHUB_OUTPUT

      
      - name: Checkout source code
        id: checkoutcode
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.setmetadata.outputs.source_repo }}
          ref: ${{ steps.setmetadata.outputs.source_tag }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the binary
        run: |
          docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry   ${{ steps.setmetadata.outputs.source_builder_image }}:${{ steps.setmetadata.outputs.source_builder_tag }}

      - name: Fetch the contract checksum
        run: |
          CHECKSUMLINE=$(grep -n ${{ steps.setmetadata.outputs.source_builder_contract_name }} artifacts/checksums.txt )
          CHECKSUM=$(echo $CHECKSUMLINE | cut -d ' ' -f 1)
          echo $CHECKSUM
